<?php
/**
 * @file
 * Colossal Menu Hooks.
 */

/**
 * Implements hook_theme().
 */
function colossal_menu_theme() {
  $theme = [];
  $theme['colossal_menu_link'] = [
    'render element' => 'elements',
    'file' => 'colossal_menu_link.page.inc',
    'template' => 'colossal_menu_link',
  ];
  $theme['colossal_menu_link_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'colossal_menu_link.page.inc',
  ];
  return $theme;
}
