# Schema for the configuration files of the Colossal menu module.

colossal_menu.menu.*:
  type: config_entity
  label: 'Menu config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

colossal_menu.link_type.*:
  type: config_entity
  label: 'Link type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

block.settings.colossal_menu_block:*:
  type: block_settings
  label: 'Colossal menu block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
